apiVersion: apps/v1
kind: Deployment
metadata:
  name: epagent
  labels:
    app: epagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epagent
  template:
    metadata:
      labels:
        app: epagent
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "epagent"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: epagent
        image: superheatedboy/epagent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: k8s-conf
              mountPath: /code
      volumes:
        - name: k8s-conf
          configMap:
            name: k8s-conf
            items:
              - key: config
                path: config
                mode: 0777 # 設定ファイルの権限
---
kind: Service
apiVersion: v1
metadata:
  name: epagent
  labels:
    app: epagent
spec:
  type: NodePort #ClusterIP
  selector:
    app: epagent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
     


# https://blog.recruit.co.jp/rmp/infrastructure/post-20439/
# kubectl create cm  k8s-conf --from-file config
