// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addFrontEpNodeRoute/{ns}/{svcname}/{frontid}/{ips}": {
            "get": {
                "description": "/addFrontEpNodeRoute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "/addFrontEpNodeRoute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "front client ID ",
                        "name": "frontid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint IP addresses",
                        "name": "ips",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/addFrontEpNodeRoute/{ns}/{svcname}/{frontid}/{nodename}": {
            "get": {
                "description": "/addFrontEpNodeRoute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "/addFrontEpNodeRoute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "front client ID ",
                        "name": "frontid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "node name",
                        "name": "nodename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/addServiceApidocUrl/{ns}/{svcname}/{apidocurl}": {
            "get": {
                "description": "addServiceApidocUrl",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "addServiceApidocUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api document url",
                        "name": "apidocurl",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/circuitBreaker/{ns}/{svcname}": {
            "get": {
                "description": "circuitBreaker defines circuit breaker policy that applies to traffic intended for a service after routing has occurred.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "traffic governance"
                ],
                "summary": "circuitBreaker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverGateway/{ns}": {
            "get": {
                "description": "discoverGateway",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "discoverGateway",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverService/{ns}/{svcname}": {
            "get": {
                "description": "discoverService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "discoverService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverServiceApidocUrl/{ns}/{svcname}": {
            "get": {
                "description": "discoverServiceApidocUrl",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "discoverServiceApidocUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverServiceEndpoints/{ns}/{svcname}": {
            "get": {
                "description": "discoverServiceEndpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "discoverServiceEndpoints",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverServiceEndpoints/{ns}/{svcname}/{nodename}": {
            "get": {
                "description": "discoverServiceEndpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "discoverServiceEndpoints",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nodename",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/discoverServices/{ns}": {
            "get": {
                "description": "discoverServices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "discoverServices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/getGatewayAddrsAndPorts": {
            "get": {
                "description": "getGatewayAddrsAndPorts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "getGatewayAddrsAndPorts",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/getGatewayPort/{ns}": {
            "get": {
                "description": "getGatewayPort",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "getGatewayPort",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/invokeService/{ns}/{svcname}": {
            "get": {
                "description": "invokeService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "invokeService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service path (ex. /path)",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/invokeServiceEndpoint": {
            "get": {
                "description": "invokeServiceEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "invokeServiceEndpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint url (ex. http://POD_IP:PORT/path)",
                        "name": "endpointurl",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/invokeServiceEndpointsByIps/{frontid}/{ns}/{svcname}": {
            "get": {
                "description": "invokeServiceEndpointsByIps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "invokeServiceEndpointsByIps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "front ID",
                        "name": "frontid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/invokeServiceEndpointsInNode/{frontid}/{ns}/{svcname}": {
            "get": {
                "description": "invokeServiceEndpointsInNode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "invokeServiceEndpointsInNode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "front ID",
                        "name": "frontid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "path (ex. /path)",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/registerGateway/{ns}/{ip}": {
            "get": {
                "description": "registerGateway",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "registerGateway",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "gateway external ip address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/registerService/{ns}/{svcname}": {
            "get": {
                "description": "registerService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serviceGovernance"
                ],
                "summary": "registerService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "svcname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/test/{id}": {
            "get": {
                "description": "テスト用APIの詳細",
                "consumes": [
                    "application/x-json-stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "必須ではありません。",
                        "name": "none",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "service registration/discovery/routing",
            "name": "serviceGovernance"
        },
        {
            "description": "traffic managemenet",
            "name": "traffic governance"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SGME API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
